name: dx_generator
description: Code generator for dx_router
version: 1.0.0
homepage: https://github.com/t0uh33d/dx

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.6
  analyzer: ">=4.6.0 <6.0.0"
  glob: ^2.1.1
  ansicolor: ^2.0.1
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
